model_name: "flux-dev"
data_config:
  train_batch_size: 1
  num_workers: 1
  img_size: 1024
  img_dir: /root/autodl-tmp/data/train
report_to: tensorboard 
train_batch_size: 1
output_dir: experiments/B_noisy_FLUX_BridgeDiff_B8_lr1e5
experiment_name: B_noisy_FLUX_BridgeDiff_B8_lr1e5
max_train_steps: 5000
learning_rate: 1e-5
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 50
checkpoints_total_limit: 1
tracker_project_name: UIR_FLUX_BridgeDiff
resume_from_checkpoint: latest
gradient_accumulation_steps: 8
train_micro_batch_size_per_gpu: 1